### PR TITLE
add maximize button for popup

### PR DESCRIPTION
**Pull request by emanueldima**
The popup looks like in the image below. We should discuss what should happen if the user clicks on the title; right now a new empty browser page is loaded with the switchboard's address. Should it behave like the maximize button?

Screenshot 2021-02-01 at 16 21 21

### CODE REVIEW

**Review by andmor- — APPROVED** [review]
Looks good to me. I propose to merge and maybe create an issue for the title link behavior?

**Comment by twagoo** [comment]
What does the maximise button do? Does it simply resize the popup? That would be expected behaviour I suppose.

I think there also should be an explicit method to switch to the 'stand-alone' switchboard with the current resource. This could be the behaviour on clicking the title but it would be more of a hidden feature (perhaps also unexpected behaviour to some users) than an explicit method to switch to the LRS proper. 

Would there be space to include a link that 'does what it says' in terms of opening the switchboard in a new tab with the selected resource?

**Comment by emanueldima** [comment]
The icon is "fullscreen" but it opens the switchboard with the current resource in a different browser window/tab, it does not affect the current tab. And clicking on the title also opens a new window/tab but without any loaded resource.

**Comment by twagoo** [comment]
Ok, I see. Let's give it a try on alpha and see if it 'feels' natural 👍

**Pull request merged**
