### PR TITLE
Bug fixes (languages in UI, errors while downloading resources)

### LINKED ISSUE #150: Allow selection of ISO 639-3 language
The list of languages selectable by the user is artificially restricted to ISO 639-1. Tools like UDPipe need the user to allow selection of languages outside this small set.

### PR DESCRIPTION
**Pull request by emanueldima**
fixes #150

### CODE REVIEW

**Review by andmor- — APPROVED** [review]
Does this also apply to current production 2.2.x?

**Comment by emanueldima** [comment]
The bugs are also in production, yes.

**Comment by andmor-** [comment]
Does not look so straight forward with the current `2.2.x` code. 
How difficult it is for you to backport this to 2.2.x in another PR?

**Comment by emanueldima** [comment]
yes: https://github.com/clarin-eric/switchboard/pull/159

**Pull request merged**
