### PR TITLE
maximize button on popup, move popup around

### PR DESCRIPTION
**Pull request by emanueldima**

### CODE REVIEW

**Comment by twagoo** [comment]
With respect to the CSS, is the idea to move it into the JS, and that applications using the popup should therefore skip loading the CSS?

**Comment by emanueldima** [comment]
Yes indeed, I'm trying to make the whole package smaller and easier to integrate. Now only the js needs to be loaded.

**Comment by emanueldima** [comment]
Yes, first the css was a copied part of bootstrap, then I started removing unneeded parts, and then I realized we only have about 7 different elements, so inline styles work just fine. The js is a bit larger but less than the sum of it and the css file, and having to do only one request is an improvement.

**Comment by andmor-** [comment]
Sounds OK but it seems to lose in terms of separation of concerns. What would be the disadvantage of loading the CSS file from withing the JS file? (so that we keep them separated)

**Comment by emanueldima** [comment]
I would argue that separation of languages is not separation of concerns. Each of the ~7 html elements of the popup has its own style which is not shared, and some positioning fields are set programmatically. I don't see much value in having a separate css file.

**Review by andmor- — APPROVED** [review]

**Pull request merged**
