### PR TITLE
Improve popup UI

### PR DESCRIPTION
**Pull request by emanueldima**
This is how the new UI would look like, please suggest improvements: 

**This is the "selection" popup:**
Screenshot 2021-11-25 at 09 59 22

**This is the normal popup:**
Screenshot 2021-11-25 at 09 59 40

**And this is the normal size site window:**
Screenshot 2021-11-25 at 09 59 53

### CODE REVIEW

**Comment by twagoo** [comment]
Definitely an improvement IMO!  Only thing I'm not too sure about the badge for local tools - the 'download' icon strongly suggests actionability to me so that can be confusing - or is it in fact meant to serve as a download link?

**Comment by emanueldima** [comment]
The badges (the round icons) are not buttons and cannot be pressed. They do show a tooltip, but not on mobile (there's no hover on mobile). I'm looking for new ways to display this information, let me know if you have ideas. Up until now we have the following badges:

1. Tool is locally installable -- not a web tool (the blue "download" badge)
2. Tool requires authentication (the orange key)
3. Tool is web based but the user must manually upload the data (WebMAUS)
4. Tool is using http instead of https (warning icon with "not secure" text message)

**Comment by twagoo** [comment]
> The badges (the round icons) are not buttons and cannot be pressed. They do show a tooltip, but not on mobile (there's no hover on mobile). I'm looking for new ways to display this information, let me know if you have ideas. Up until now we have the following badges:
> 
>     1. Tool is locally installable -- not a web tool (the blue "download" badge)

I can't think of a perfect icon, but perhaps this is better than the 'download' one?
https://fontawesome.com/v5.15/icons/desktop?style=solid
image


> 
>     2. Tool requires authentication (the orange key)

The key works well for me. Maybe we should be careful not too use too many different colours... We can discuss :)

Alternative suggestion from Font Awesome:
https://fontawesome.com/v5.15/icons/user-shield?style=solid
image

>     3. Tool is web based but the user must manually upload the data (WebMAUS)

Is an icon needed for this? Such tools will only show up in the inventory, isn't it? I see that an 'upload' icon is used, which to me seems to do the job.

>     4. Tool is using http instead of https (warning icon with "not secure" text message)

I think we should stick with the `⚠️ Not secure` icon + text solution.

**Comment by emanueldima** [comment]
I changed the badges to show some text, which I think is less confusing. Thanks for feedback!

**Comment by andmor-** [comment]
I am working on a new docker build image. This should fix the CI

**Comment by andmor-** [comment]
OK. The docker build now supports multi-architecture systems.
To fix, the build the environment needed two changes:
1. Upgrade npm
2. Install python3. For some reason this is now needed, any idea why?

**Comment by emanueldima** [comment]
The python requirement comes from sass, I'm afraid. It's much nicer to develop with scss, but there are clear downsides :(

**Pull request merged**
