### PR TITLE
Compact UI for improved mobile use

### PR DESCRIPTION
**Pull request by emanueldima**
[EDITED]
- Tried to make a more compact UI for better mobile usage: the tool titles are rendered on a single line, the Resource section takes less space and displays the file size, moved the tools controls in line with the title. 

- Added "key" badge for tools with non-null authentication strings. This was a request from discussions with CLARIAH partners, to bring to user's attention that the tool is behind a login screen. Also added  a "shield" badge for tools that have https urls (we will make a new tool config entry for this).

Screen Shot 2020-05-25 at 11 53 48

Screen Shot 2020-05-25 at 12 01 41

### CODE REVIEW

**Comment by emanueldima** [comment]
I guess you refer to the use of "floats"? I tried using the bootstrap grid, but the columns have a fixed split ratio, and this leads to an inefficient usage of space. The floats use the same line if the contents fits (left side + right side).

**Comment by twagoo** [comment]
@emanueldima no, I do mean the grid system. As far as I understand them, and also from my experience, the 12 grid units normally provide sufficient flexibility. It makes for a very predictable layout (the same cannot be said about floats in my experience 😬) but I can imagine that in some corner cases they can be too restrictive. The approach that I had in mind would be the typical one where you distribute a set of UI components over divs that are columns on medium to large displays, but revert to individual rows on smaller screens. Have you considered this specific approach?

**Comment by emanueldima** [comment]
@twagoo Yes, AFAIK the bootstrap grid is based on a fixed split ratio. So the left side must fit in (let's say) 2/3 of the space and the right side in 1/3, otherwise each side will be rendered separately on different lines. I am using the grid elsewhere, but in this case it was using more space.

**Comment by twagoo** [comment]
This is true, the grid sets a fixed width ratio for all the columns given a 'screen width class'. If we need more flexibility than that, your current solution seems sensible enough

**Pull request merged**
